record_store/record_store/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('inventory/', include('inventory.url')),
    path('admin/', admin.site.urls),
]

record_store/inventory/models.py
from django.db import models

class Artist(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Album(models.Model):
    title = models.CharField(max_length=255)
    year = models.IntegerField()
    stock_level = models.IntegerField()
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


# Create your models here.

record_store/inventory/views.py
from django.shortcuts import render
from django.http import HttpResponse
from inventory.models import *

def index(request):
    artists = Artist.objects.all()
    return render(request, "inventory/index.html", locals())


# Create your views here.

record_store/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Bob's Record Store</title>
  </head>
  <body>
   {% block content %}
   
   {% endblock %}
  </body>
</html>

record_store/templates/inventory/index.html
{% extends "base.html" %}

{% block content %}

  {% for artist in artists %}
    <h2>{{ artist.name }}</h2>

    <ul>
      {% for album in artist.album_set.all %}
        <li>{{ album.title}} - {{ album.year }}</li>
        {% endfor %}
    </ul>

  {% endfor %}

{% endblock %}